"""foreign key test

Revision ID: 431485475514
Revises: 92d113053ad9
Create Date: 2020-07-17 17:54:25.276665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431485475514'
down_revision = '92d113053ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_host_ip'), ['ip'])
        batch_op.create_foreign_key(batch_op.f('fk_host_cpu_component'), 'component', ['cpu'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_host_cpu_component'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_host_ip'), type_='unique')

    # ### end Alembic commands ###
