"""HostComponents

Revision ID: 436ca5d59827
Revises: fe5efe6ad930
Create Date: 2020-07-20 16:27:32.202816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436ca5d59827'
down_revision = 'fe5efe6ad930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostcomponent',
    sa.Column('hostID', sa.Integer(), nullable=False),
    sa.Column('componentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['componentID'], ['component.id'], name=op.f('fk_hostcomponent_componentID_component')),
    sa.ForeignKeyConstraint(['hostID'], ['host.id'], name=op.f('fk_hostcomponent_hostID_host')),
    sa.PrimaryKeyConstraint('hostID', 'componentID', name=op.f('pk_hostcomponent'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hostcomponent')
    # ### end Alembic commands ###
