"""Changed Reservation table name

Revision ID: 78d66e86d545
Revises: 436ca5d59827
Create Date: 2020-07-21 16:26:37.210535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d66e86d545'
down_revision = '436ca5d59827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('hostID', sa.Integer(), nullable=True),
    sa.Column('reservation_type', sa.Integer(), nullable=True),
    sa.Column('begin_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['hostID'], ['host.id'], name=op.f('fk_reservation_hostID_host')),
    sa.ForeignKeyConstraint(['reservation_type'], ['reservation_type.id'], name=op.f('fk_reservation_reservation_type_reservation_type')),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name=op.f('fk_reservation_userID_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    op.drop_table('reservations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userID', sa.INTEGER(), nullable=True),
    sa.Column('hostID', sa.INTEGER(), nullable=True),
    sa.Column('reservation_type', sa.INTEGER(), nullable=True),
    sa.Column('begin_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['hostID'], ['host.id'], ),
    sa.ForeignKeyConstraint(['reservation_type'], ['reservation_type.id'], name='fk_reservations_reservation_type_reservation_type'),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_reservations')
    )
    op.drop_table('reservation')
    # ### end Alembic commands ###
