"""reservations

Revision ID: fe5efe6ad930
Revises: 431485475514
Create Date: 2020-07-17 19:08:35.354007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5efe6ad930'
down_revision = '431485475514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_type'))
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('hostID', sa.Integer(), nullable=True),
    sa.Column('reservation_type', sa.Integer(), nullable=True),
    sa.Column('begin_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['hostID'], ['host.id'], name=op.f('fk_reservations_hostID_host')),
    sa.ForeignKeyConstraint(['reservation_type'], ['reservation_type.id'], name=op.f('fk_reservations_reservation_type_reservation_type')),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name=op.f('fk_reservations_userID_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('reservation_type')
    # ### end Alembic commands ###
